# Generated by Django 3.2.12 on 2022-07-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='is_completed',
        ),
    ]
